config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :categories
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  resources :orders do 
    resources:orderitems
  end
  
  resources :contacts, only: [:new, :create]

  devise_for :admins
  
  devise_for :users do
    resources :orders
  end
  
  match 'users/:id' => 'user#destroy', :via => :delete, :as => :admin_destroy_user
  
  get 'cart/index'
  resources :items
  
  # Stripe resources
  resources :charges
  
  root 'static_pages#home'
  
  get "/users" => 'user#show'

  # Static pages routes
  get '/home' => 'static_pages#home'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/items' => 'items#index'
  
  # Users routes
  get '/login' => 'user#login'
  get '/logout' => 'user#logout'
  get '/admin/login' => 'admin#login'
  get '/admin/logout' => 'admin#logout'
  
  # Cart routes
  get '/cart/clear' => 'cart#clearCart'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  
  get '/checkout' => 'cart#createOrder'
  
  get '/checkout/:price' => 'cart#clearOrder'
  
  get '/key/finishOrder' => 'key#finishOrder', :as => :finishOrder
  
  # Devise routes
  root :to => 'site#home'
  
  # Orders routes
  get '/orders' => 'order#show'
  get '/paid/:id' => 'static_pages#paid'
  
  # Admin orders
  get '/adorders' => 'orders#adminorders'
  
  # Paypal route
  get '/thanks/:id' => 'static_pages#thanks'
  
  # Category routes
  get 'category/:title', to: 'static_pages#category'
  
  # Search routes
  post '/search' => 'items#search'
  
  # Profile route
  # get 'confirmations/edit' => 'confirmations#edit'
  get '/profile' => 'static_pages#profile'
  
  # Error routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  # Translation
  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'static_pages#home', as: 'index', via: :all
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/contact.rb
class Contact < MailForm::Base
   attribute :name, :validate => true
   # email regex validation (needs @ etc)
   attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
   attribute :message, :validate => true
   # to prevent span
   attribute :seguridad, :captcha => true
   
   def headers
        {
            :subject => "Contact Form",
            :to => "jagonzacas@hotmail.com",
            :from => %("#{name}" <#{email}>)
        }
   end
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
  
    def order_params
        params.require(:order).permit( :order_date, :user_id, :status)
    end

    has_many :orderitems, :dependent => :delete_all
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :remember_me)
  end

  has_many :orders, dependent: :destroy

end

app/controllers/key_controller.rb
class KeyController < ApplicationController
   def finishOrder
    @orderID = params[:oi]
    @user = User.find(current_user.id)
    @orderitems = Orderitem.where(order_id: Order.last)
    @linetotal = params[:price]
  end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  before_action :authenticate_user!, only: [:profile]

  def home
    if params[:set_locale]
      redirect_to index_url(locale: params[:set_locale])
    else
      @categories = Category.all
      @items = Item.all
    end
  end

  def contact
  end

  def about
  end
  
  def profile
    @orders = Order.where(user_id: current_user.id)
    @users = User.where(email: current_user.email)
  end
  
  def createOrder
    # Step 1: Get the current user
   @user = User.find(current_user.id)
  
   # Step 2: Create a new order and associate it with the current user
   @order = @user.orders.build(:order_date => DateTime.now, :status => 'Pending')
   @order.save
  
   # Step 3: For each item in the cart, create a new item on the order!!
   @cart = session[:cart] || {} # Get the content of the Cart
   @cart.each do | id, quantity |
     item = Item.find_by_id(id)
     @orderitem = @order.orderitems.build(:item_id => item.id, :title => item.title, :description => item.description, :quantity => quantity, :price=> item.price)
     @orderitem.save
   end
   
   @orders = Order.all
   @orderitems = Orderitem.where(order_id: Order.last)
   session[:cart] = nil
  end
  
  def paid
    
    #@actual = Order.find(params[:id])
    
    #unless @log.user_id == current_user.id
      # flash[:error] = "unauthorized"
      # redirect_to :index
    #end
    
    # redirect_to "/cart/clear"
    flash[:notice] = 'Transaction Complete'
    @order = Order.find(params[:id])
    @order.update_attribute(:status , "Paid with Stripe: #{current_user.email}")
    # redirect_to "/paid/#{@orderNum}"
    #"Paid by User:#{current_user.id} #{current_user.name} #{current_user.surname}")
  end

  def thanks
     @order = Order.find(params[:id])
     @order.update_attribute(:status, "Paid with PayPal")
  end
  
  def category
    catName = params[:title]
    @items = Item.where("category like ? ", catName)
  end
  
  def contacto
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/static_pages/about.html.erb
<%# StaticPages#about %>
<%# Find me in app/views/static_pages/about.html.erb %>
<h1>About Us</h1>
</br>
</br>
<h2>Teaching and imparting knowledge is the most ancient way by which humanity finds means to evolve. </h1>
</br>
<p>The passing of acquired knowledge and wisdom allows for the future generations to move on to newer grounds and better days, improving our existence at every generation.</p>
</br>
<p>Although some apprentices have the maturity to appreciate and enjoy learning, that sensation can never compare to the actual joy of teaching. It is a selfless deed consisting in sharing that which is most valuable to men and thinking only of those who are yet to be.</p>
</br>
<p>It is this very passion and respect for the act of teaching that brought to our attention the need for a place where the curious minded can go and acquire technology knowledge on demand. A place that provides the required teachings on the selected subject that can be accessed according to the modern lifestyle constraints and limitations.</p>
</br>
<p>Lessons can be easily searched for by subject and proficiency level. A library will be formed and students will be able to start and pick up where they left whenever it is convenient to them.</p>
</br>
<p>Teachers can offer their lessons with ease and be compensated for it. Also, there is no stop to learning so why not have some lessons themselves?</p>
</br>
<p>We propose a one way stop to both teachers and students to share and acquire knowledge, each getting their compensation in the coin they seek.</p>
</br>

<h3> We commit to bringing down the barriers and be a part of humanity’s evolution.</h3>

app/views/static_pages/category.html.erb
<% if @items.length == 0  %>
    <br />
    <h2>There are currently no products in this category</h2>
<% end %>

<p id="notice"><%= notice %></p>
<div id="itemsContainer">
<h1>Items</h1>
    <% @items.each do |item| %>
        <div class="entry">
            <h2><%= item.title %></h2>
            <%= link_to (image_tag item.image_url), item %>
            
            <p><%= sanitize(item.description) %></p>
            <p class="tag">Lecturer: </p><%= item.lecturer %>
            <p class="tag">Price: </p>
            <span class="price"><%= number_to_currency(item.price, :unit => "€ ") %></span>
            <p class="tag">Category: </p><%= item.category %>
            
            <% if user_signed_in? %>
            <p>        
                <a href="/cart/<%= item.id %>" class="button">Add to Cart</a>  
                <%= link_to 'Show', item, :class =>"button", :role=>"button" %>
                <% if current_user.try(:admin?) %> 
                <%= link_to 'Edit', edit_item_path(item), :class =>"button", :role=>"button" %>
                <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"button", :role=>"button" %>
                <% end %>
            </p>
            <% end %>
        </div>
    <% end %>
<br>

app/views/static_pages/home.html.erb
<%# Line below displays messages like "You have logged in" %>
<p id="notice"><%= notice %></p>

<h1><%= t('.welcome') %></h1>

<br />
<h3><%= t('.categories') %></h3>
<%=render 'layouts/categories'%>
<br />
<h3><%= t('.hottest') %></h3>
<%=render 'layouts/popular'%>

app/views/static_pages/paid.html.erb
<!-- Stripe redirects you to this -->
<p>Thank you for your payment</p>
<p>Your order will be placed soon</p>
<%= image_tag("thanks.jpg", :alt => "Delivery Cart", :style => "width: 150px") %>
<% @@totalqty = 0 %>
<% @@totalDisplayed = 0 %>

app/views/static_pages/profile.html.erb
<p id="notice"><%= notice %></p>
<h1>My Profile</h1>
<h3>User Details</h3>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Last Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.firstname %></td>
        <td><%= user.surname %></td>
        <td><%= user.address %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
      </tr>
      <% if user.firstname.nil? || user.surname.nil? || user.address.nil? || user.phone.nil? %>
        <p>Feel free to add missing details in your profile.</p>
      <% end %>
    <% end %>
  </tbody>
</table>
<% unless current_user.try(:admin?) %>
<h3>My Orders</h3>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Date</th>
      <th>User Id</th>
      <th>Status</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.order_date.strftime("%F %T") %></td>
        <td><%= order.user_id %></td>
        <td><%= order.status %></td>
        <td><%= order.updated_at.strftime("%F %T") %></td>
        <td><span class="button"><%= link_to 'Show', order %></span></td>
        <% if current_user.try(:admin?) %>
            <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% end %>
<br>
<br>
<br>
<% if current_user.try(:admin?) %>
  <span class="button">
    <%= link_to "Quit Being an Admin", registration_path(current_user), data: { confirm: 
      "Are you sure? You will not be able to log in as an admin again" }, method: :delete %>
  </span>
<% end %>

app/views/static_pages/thanks.html.erb
<!-- Paypal redirects you to this -->
<p>Thank you for your payment</p>
<p>Your order will be placed soon</p>
<%= image_tag("thanks.jpg", :alt => "Delivery Cart", :style => "width: 150px") %>
<% @@totalqty = 0 %>
<% @@totalDisplayed = 0 %>