config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :categories
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  resources :orders do 
    resources:orderitems
  end
  
  resources :contacts, only: [:new, :create]

  devise_for :admins
  
  devise_for :users do
    resources :orders
  end
  
  match 'users/:id' => 'user#destroy', :via => :delete, :as => :admin_destroy_user
  
  get 'cart/index'
  resources :items
  
  # Stripe resources
  resources :charges
  
  root 'static_pages#home'
  
  get "/users" => 'user#show'

  # Static pages routes
  get '/home' => 'static_pages#home'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/items' => 'items#index'
  
  # Users routes
  get '/login' => 'user#login'
  get '/logout' => 'user#logout'
  get '/admin/login' => 'admin#login'
  get '/admin/logout' => 'admin#logout'
  
  # Cart routes
  get '/cart/clear' => 'cart#clearCart'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  
  get '/checkout' => 'cart#createOrder'
  
  get '/checkout/:price' => 'cart#clearOrder'
  
  get '/key/finishOrder' => 'key#finishOrder', :as => :finishOrder
  
  # Devise routes
  root :to => 'site#home'
  
  # Orders routes
  get '/orders' => 'order#show'
  get '/paid/:id' => 'static_pages#paid'
  
  # Admin orders
  get '/adorders' => 'orders#adminorders'
  
  # Paypal route
  get '/thanks/:id' => 'static_pages#thanks'
  
  # Category routes
  get 'category/:title', to: 'static_pages#category'
  
  # Search routes
  post '/search' => 'items#search'
  
  # Profile route
  # get 'confirmations/edit' => 'confirmations#edit'
  get '/profile' => 'static_pages#profile'
  
  # Error routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  # Translation
  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'static_pages#home', as: 'index', via: :all
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if params[:set_locale]
      redirect_to store_url(locale: params[:set_locale])
    else
      @items = Item.all
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def search
     
     if params[:nombre].present?
       @search_term = params[:nombre]
       @items = Item.where("title like ?", "%#{params[:nombre]}%",)
     elsif params[:categoria].present?
       @search_term = params[:categoria]
       @items = Item.where("category like ?", "%#{params[:categoria]}%" )
     elsif params[:skill].present?
       @search_term = params[:skill]
       @items = Item.where("skill_level like ?", "%#{params[:skill]}%")
     elsif params[:precio].present?
       @search_term = params[:precio]
        @items = Item.where("price between ? AND ?", "#{params[:precio]}".split('-')[0], "#{params[:precio]}".split('-')[1] )
     end
     
      # @items = Item.where("title like ? or category like ? or skill_level like ? or price between ? AND ?", 
      # "%#{params[:nombre]}%", "%#{params[:categoria]}%", "%#{params[:skill]}%",
      # "#{params[:precio]}".split('-')[0], "#{params[:precio]}".split('-')[1] )
     
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :lecturer, :price, :image_url, :category, :skill_level)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :lecturer %>
    <%= form.text_field :lecturer %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :skill_level %>
    <%= form.text_field :skill_level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<% if current_user.try(:admin?) %>
  <h3>Feel free to add some more products!</h3>
<% end %>

<table>
  <tbody>
    <% @items.each do |item| %>
      <div class="entry">
        <%= image_tag(item.image_url) %>
        <h3><%= item.title %></h3>
        <p><%= sanitize(item.description) %></p>
        <p class="tag">Lecturer: </p><%= item.lecturer %>
        <p class="tag">Price: </p>
        <span class="price"><%= number_to_currency(item.price, :unit => "€ ") %></span>
        <p class="tag">Category: </p><%= item.category %>
        <% if user_signed_in? %>
        <% unless current_user.try(:admin?) %>
        <a href="/cart/<%= item.id %>" class= "button"> Add to Cart</a>
        <% end %>
        <span class="button"><%= link_to 'Show', item %></span>
        <% end %>
        <% if current_user.try(:admin?) %>
          <span class="button"><%= link_to 'Edit', edit_item_path(item) %></span>
          <span class="button"><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        <% end %>
      </div>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.try(:admin?) %>
  <span class="button"><%= link_to 'New Item', new_item_path %></span>
<% end %>




<% if false %>
<tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.lecturer %></td>
        <td><%= item.price %></td>
        <td><%= item.image_url %></td>
        <td><%= item.category %></td>
        <td><%= item.skill_level %></td>
        <td><a href="/cart/<%= item.id %>" class= "button"> Add to Cart</a></td>
        <td><%= link_to 'Show', item %></td>
        <% unless user_signed_in? %>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      
      
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<h2>You Searched Our Product Catalog For <%= @search_term %></h2>

<% if @items.length == 0  %>
<br />
<h2>No products were found to match your search</h2>
<% end %>


<table class="catalog">
  <% @items.each do |item| %>
      <tr>
        <td>
          <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
          </div>
          <div class="title">
            <%= link_to item.title, item %>
          </div>
          <div class="description">
            <%= item.description %>
          </div>  
          <div class="price">
             <%= number_to_currency(item.price, :unit => "€") %>
          </div>
          <div class="links">
            <% if current_user.try(:admin?) %>
              <%= link_to 'Edit', edit_item_path(item) %>
              <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%else%>
              <span class="button"><a href="/cart/<%= item.id %>">Add to Cart</a></span>
            <%end%>  
        </div>
        </td>
      </tr>
    <% end %>
</table>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Lecturer:</strong>
  <%= @item.lecturer %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Skill level:</strong>
  <%= @item.skill_level %>
</p>

<% if current_user.try(:admin?) %>
<span class="button"><%= link_to 'Edit', edit_item_path(@item) %></span> |
<% end %>
<span class="button"><%= link_to 'Back', items_path %></span>
<%#= link_to 'Add to Cart', {:controller => 'cart', :action => 'add', :param => @item.id} %>