config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :categories
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  resources :orders do 
    resources:orderitems
  end
  
  resources :contacts, only: [:new, :create]

  devise_for :admins
  
  devise_for :users do
    resources :orders
  end
  
  match 'users/:id' => 'user#destroy', :via => :delete, :as => :admin_destroy_user
  
  get 'cart/index'
  resources :items
  
  # Stripe resources
  resources :charges
  
  root 'static_pages#home'
  
  get "/users" => 'user#show'

  # Static pages routes
  get '/home' => 'static_pages#home'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/items' => 'items#index'
  
  # Users routes
  get '/login' => 'user#login'
  get '/logout' => 'user#logout'
  get '/admin/login' => 'admin#login'
  get '/admin/logout' => 'admin#logout'
  
  # Cart routes
  get '/cart/clear' => 'cart#clearCart'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  
  get '/checkout' => 'cart#createOrder'
  
  get '/checkout/:price' => 'cart#clearOrder'
  
  get '/key/finishOrder' => 'key#finishOrder', :as => :finishOrder
  
  # Devise routes
  root :to => 'site#home'
  
  # Orders routes
  get '/orders' => 'order#show'
  get '/paid/:id' => 'static_pages#paid'
  
  # Admin orders
  get '/adorders' => 'orders#adminorders'
  
  # Paypal route
  get '/thanks/:id' => 'static_pages#thanks'
  
  # Category routes
  get 'category/:title', to: 'static_pages#category'
  
  # Search routes
  post '/search' => 'items#search'
  
  # Profile route
  # get 'confirmations/edit' => 'confirmations#edit'
  get '/profile' => 'static_pages#profile'
  
  # Error routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  # Translation
  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'static_pages#home', as: 'index', via: :all
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/contact.rb
class Contact < MailForm::Base
   attribute :name, :validate => true
   # email regex validation (needs @ etc)
   attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
   attribute :message, :validate => true
   # to prevent span
   attribute :seguridad, :captcha => true
   
   def headers
        {
            :subject => "Contact Form",
            :to => "jagonzacas@hotmail.com",
            :from => %("#{name}" <#{email}>)
        }
   end
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
  
    def order_params
        params.require(:order).permit( :order_date, :user_id, :status)
    end

    has_many :orderitems, :dependent => :delete_all
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :remember_me)
  end

  has_many :orders, dependent: :destroy

end

app/controllers/key_controller.rb
class KeyController < ApplicationController
   def finishOrder
    @orderID = params[:oi]
    @user = User.find(current_user.id)
    @orderitems = Orderitem.where(order_id: Order.last)
    @linetotal = params[:price]
  end 
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_categories.html.erb
<br>

<table>
  <tbody>
    <% @categories.each do |category| %>
      <div class="entry">
        <%= link_to (image_tag category.image, :class=>"itemholsIm"), category %>
        <h3><%= category.title %></h3>
        <p><%= sanitize(category.description) %></p>
          
          <% @title = category.title %>
          <span>&emsp;</span><span>&emsp;</span><span>&emsp;</span>
          <span>&emsp;</span><span>&emsp;</span><span>&emsp;</span>
          <span>&emsp;</span>
          <span class="button"><%= link_to t('.check') + @title + t('.products'), 
              :controller => 'static_pages', :action => 'category', :title => @title %></span>
          
      </div>
    <% end %>
  </tbody>
</table>

app/views/layouts/_popular.html.erb
<%= stylesheet_link_tag "popular" %>

<table>
  <tbody>
    <% @items.limit(2).order(:id).each do |item| %>
      <div class="entry">
        <%= image_tag(item.image_url) %>
        <h3><%= item.title %></h3>
        <p><%= sanitize(item.description) %></p>
        <p class="tag"><%=t('.lecturer')%>: </p><%= item.lecturer %>
        <p class="tag"><%=t('.price')%>: </p>
        <span class="price"><%= number_to_currency(item.price, :unit => "€ ") %></span>
        <% if user_signed_in? %>
        <a href="/cart/<%= item.id %>" class= "button"><%= t('.addToCart') %></a>
        <span class="button"><%= link_to t('.show'), item %></span>
        <% end %>
        <% if current_user.try(:admin?) %>
          <span class="button"><%= link_to 'Edit', edit_item_path(item) %></span>
          <span class="button"><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        <% end %>
      </div>
    <% end %>
  </tbody>
</table>

app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post", :class => "form-inline") do %>
    <%= label_tag(t('.course_name')) %>
    <%= text_field_tag(:nombre) %>
    
    <%= label_tag(t('.category')) %>
    
    <%= select_tag "categoria", options_for_select(["Web", "Software"]), :include_blank => true %>
    
    <%= label_tag(t('.skill_level')) %>
    
    <%= select_tag "skill", options_for_select(["Beginner", "Advanced"]), :include_blank => true %>
    
    <%= label_tag(t('.price_range')) %>
    
    <%= select_tag "precio", options_for_select(["1-50", "50-100", "100-150"]), :include_blank => true %>
    
    <%= submit_tag(t('.search')) %>
<% end %>
<pre></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeWorld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <!-- The following clears the current item qty and sub total that displays through all pages
  when the user signs out -->
  <% unless user_signed_in? %>
    <% @@totalqty = 0 %>
    <% @@totalDisplayed = 0 %>
  <% end %>
  
  <!-- The following deals with class variable initialization issues -->
  <% unless @@totalqty ||= 0 && @@totalDisplayed ||= 0 %>
    <% @items = 0 %>
    <% @total = 0 %>
  <% else %>
    <% @items = @@totalqty %>
    <% @total = @@totalDisplayed %>
  <% end %>
  
  <% unless current_user.try(:admin?) %>
    <p style="text-align:right;">
      <% if user_signed_in? %>
    <b>Last time you logged in:</b> <%= current_user.last_sign_in_at.strftime("%F %T") %>
  <% end %><b>Cart Items:</b> <%= @items %> | 
      <b>SubTotal:</b> <%= number_to_currency(@total, :unit => "€ ") %></p>
  <% end %>
  
  <header class="headSec">
    <ul>
      <li class="logo"><%= link_to t('.codeWorld'), '/home' %></li>
      
      <% if user_signed_in? %>
        <li>
          <a href="https://a36a883947b94457b231ac5604f5b6f9.vfs.cloud9.us-east-2.amazonaws.com/profile">
            <%=t('.hi')%> <%= current_user.email %>
          </a>
        </li>
      <% end %>
      
      <% if user_signed_in? %>
        <li><%= link_to t('.logout'), destroy_user_session_path, :method => :delete %></li>
      <% unless current_user.try(:admin?) %>
        <li><%= link_to t('.view_orders'), orders_path %></li>
        <li><%= link_to t('.cart'), cart_path  %></li>
      <% end %>
        <li><%= link_to t('.view_profile'), '/profile' %></li>
        <li><%= link_to t('.edit_details'), edit_user_registration_path %></li>
        
      <% else %>
        <li><%= link_to t('.register'), new_user_registration_path %></li> 
        <li><%= link_to t('.login'), new_user_session_path %></li>
      <% end %>
      
      <% if current_user.try(:admin?) %>
        <li><%= link_to "View Orders", '/adorders' %></li>
        <li><%= link_to "Users", '/users' %></li>
      <% end %>
      
        <li><%= link_to t('.items'), '/items' %></li>
      <% if current_user.try(:admin?) %>
        <li style="color:#1a1aff;padding-top:14px;font-weight:bold;">Admin Session</li>
      <% end %>
      <% unless current_user.try(:admin?) %>
        <li><%= link_to t('.contact'), '/contacts/new' %></li>
        <li><%= link_to t('.about'), '/about' %></li>
        <li><%= link_to t('.home'), '/home' %></li>
      <% end %>

    </ul>
    
  </header>
  <%# Language Switcher %>
  <%= form_tag index_path, class: 'locale' do %>
    <%= select_tag 'set_locale',
      options_for_select(LANGUAGES, I18n.locale.to_s),
      onchange: 'this.form.submit()' %>
    <%#= submit_tag 'submit' %>
    <%= javascript_tag "$('.locale input').hide()" %>
  <% end %>

  <body>
    <div class="busqueda">
    <%=render 'layouts/search'%>
    </div>
    <%= yield %>
    </div>
  </body>
  
  <footer class="foot">
    <p><%= t('.social') %></p>
    <p><%= t('.copyright') %></p>
    <% if current_user.try(:admin?) %>
      <%= link_to 'New Category', new_category_path, :class =>"button", :role=>"button" %>
    <% end %>
  </footer>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<p id="notice"><%= notice %></p>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>